"""empty message

Revision ID: d24d61a0c751
Revises: d7371b87f023
Create Date: 2021-11-08 09:52:07.690171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24d61a0c751'
down_revision = 'd7371b87f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
