"""empty message

Revision ID: d7371b87f023
Revises: 8d05b1f4ec00
Create Date: 2021-11-08 09:22:44.318916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7371b87f023'
down_revision = '8d05b1f4ec00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('img', sa.String(), nullable=True))
    op.add_column('item', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_constraint('item_barcode_key', 'item', type_='unique')
    op.create_index(op.f('ix_item_created_on'), 'item', ['created_on'], unique=False)
    op.drop_column('item', 'barcode')
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_exp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'token_exp')
    op.drop_column('user', 'token')
    op.add_column('item', sa.Column('barcode', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_item_created_on'), table_name='item')
    op.create_unique_constraint('item_barcode_key', 'item', ['barcode'])
    op.drop_column('item', 'created_on')
    op.drop_column('item', 'img')
    # ### end Alembic commands ###
